### ISSUE TITLE
shuffle(again)

### ISSUE THREAD

**Issue by Moonlite-Kitsune** [DanThePythonMan/BlackJackJS#8]
frickin broke reshuffling again, cba to fix it rn

**Comment by Stanley7425** [comment]
We're no strangers to love
You know the rules and so do I (do I)
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it (say it)
Inside, we both know what's been going on (going on)
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it (to say it)
Inside, we both know what's been going on (going on)
We know the game and we're gonna play it
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

**Comment by jadedgal** [comment]
> frickin broke reshuffling again, cba to fix it rn

lmao, idk what to do. is it the reshuffle? just rebuild the deck idk

**Comment by Moonlite-Kitsune** [comment]
honestly neither, i can work on it i spose, i think i know what i meant by that

**Comment by Moonlite-Kitsune** [comment]
yeah i know what i meant now

**Comment by Moonlite-Kitsune** [comment]
think it should be fixed now, splits disabled for now cause its giving me a headache

**Comment by Moonlite-Kitsune** [comment]
probably fixed for good now
